# Generated by Django 3.0.5 on 2022-01-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220109_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='category_status',
        ),
    ]
