# Generated by Django 2.2.13 on 2022-01-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
    ]
