# Generated by Django 2.2.13 on 2022-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AlterField(
            model_name='products',
            name='availabilty',
            field=models.CharField(max_length=100),
        ),
    ]
