# Generated by Django 2.2.13 on 2022-01-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220104_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
