# Generated by Django 2.2.13 on 2022-01-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
