# Generated by Django 3.0.5 on 2022-01-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220107_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qty',
            field=models.IntegerField(max_length=255),
        ),
    ]
