# Generated by Django 3.0.5 on 2022-01-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220110_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
