# Generated by Django 3.0.5 on 2022-01-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220112_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='attribute_id',
        ),
    ]
