# Generated by Django 2.2.13 on 2022-01-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('gross_amount', models.CharField(max_length=255)),
                ('service_charge_rate', models.CharField(max_length=255)),
                ('service_charge', models.CharField(max_length=255)),
                ('vat_charge_rate', models.CharField(max_length=255)),
                ('vat_charge', models.CharField(max_length=255)),
                ('net_amount', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('paid_status', models.IntegerField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
