# Generated by Django 2.2.13 on 2022-01-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='paid_status',
            field=models.IntegerField(),
        ),
    ]
