# Generated by Django 2.2.13 on 2022-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220103_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='paid_status',
            field=models.CharField(max_length=100),
        ),
    ]
