# Generated by Django 2.2.13 on 2022-01-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220104_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='oder',
            name='customer_phone_number',
            field=models.IntegerField(default=10),
        ),
    ]
