# Generated by Django 2.2.13 on 2022-01-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220107_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='paid_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=100),
        ),
    ]
