# Generated by Django 3.0.5 on 2022-01-10 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220110_1942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_auto_20220109_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Oders_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('gross_amount', models.IntegerField()),
                ('oder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Oder')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
